logLevel: INFO
messages:
    colorCode: '§'
    requiresPlayer: '-> §cOnly in-game players§7 can use the {1} command' # 1 = Command Label
    requiresArgument: '-> §7Required §cargument missing§7: §7§o{1}' # 1 = Argument Name
    unknownArgument: '-> §eUnable to determine §o{1}§7: §f§o{2}' # 1 = Argument Name, 2 = Argument Value
    reload: '-> §7{1} plugin §2reloaded' # 1 = Plugin Name
version: @VERSION@