name: BukkitPlugin
version: @VERSION@
description: Template code used for Bukkit plugins
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman/BukkitPlugin
main: edgruberman.bukkit.bukkitplugin.Main
commands:
  'bukkitplugin:action':
    aliases: [action, bukkitplugin.action]
    description: Do something
    permission: bukkitplugin.action
    usage: '§f-> §7Usage: §b/<command> §3§otype §3[§oplayer§3]'
  'bukkitplugin:reload':
    description: Reload BukkitPlugin plugin
    permission: bukkitplugin.reload
    usage: '§f-> §7Usage: §b/<command>'
permissions:
  bukkitplugin.admin:
    description: Can use all features
    default: op
    children:
      bukkitplugin.user: true
      bukkitplugin.reload: true
  bukkitplugin.user:
    description: Can use basic features
    default: true
    children:
      bukkitplugin.action: true
  bukkitplugin.action:
    description: Can use action command
    default: false
  bukkitplugin.reload:
    description: Can use reload command
    default: false