name: @NAME@
version: @VERSION@
description: Template code used for Bukkit plugins
author: EdGruberman (ed@rjump.com)
website: http://github.com/EdGruberman
main: edgruberman.bukkit.simpletemplate.Main
commands:
    'simpletemplate:command.action':
        aliases: [action, command.action]
        description: Reload SimpleTemplate plugin
        permission: simpletemplate.command.action
        usage: /<command>
    'simpletemplate:reload':
        description: Reload SimpleTemplate plugin
        permission: simpletemplate.reload
        usage: /<command>
permissions:
    simpletemplate.user:
        description: Can use basic information commands
        default: true
        children:
            simpletemplate.command.action: true
    simpletemplate.admin:
        description: Can use all commands
        default: op
        children:
            simpletemplate.user: true
            simpletempate.reload: true