name: @NAME@
description: Template code used for Bukkit plugins
version: @VERSION@
author: @AUTHOR@
main: @MAIN@
commands:
    'simpletemplate:command.action':
        aliases: [action, command.action]
        description: Reload SimpleTemplate plugin
        permission: simpletemplate.command.action
        usage: /<command>
    'simpletemplate:reload':
        description: Reload SimpleTemplate plugin
        permission: simpletemplate.reload
        usage: /<command>
permissions:
    simpletemplate.info:
        description: Can use basic information commands
        default: true
        children:
            simpletemplate.command.action: true
    simpletemplate.admin:
        description: Can use all commands
        default: op
        children:
            simpletemplate.info: true
            simpletempate.reload: true